name: flux
description: "Flux: The habit changer"
publish_to: "none"

version: 2.1.2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  fl_chart:
  path_provider:
  shared_preferences:
  intl:
  flutter_svg: ^2.0.10


  share_plus:
  csv: ^6.0.0
  syncfusion_flutter_charts:

  collection:

  uuid:
  archive: ^3.6.1
  permission_handler:
  lottie:
  file_picker: ^11.0.2


  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path:

  timezone:
  flutter_riverpod:
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2
  drift_sqflite: ^2.0.1
  sqlite3: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.20.0
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - icon.svg

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "icons/icon.png"
  image_path: "icons/icon.png"
